Feature/add home page with seed refactor
Zhi0105/rails-base-project pull request #13
Opened 2022-03-02 17:43 UTC by Zhi0105

## Summary
- add home page as root path
- add sign out button on trader dashboard
- refactoring seed file by creating services folder in order to organize fetching data
- modifying rspec testing for sign in and sign out of both admin and trader cause of adjustment

## Screenshot
![Capture](https://user-images.githubusercontent.com/88585596/156417698-7ffed0d3-a5b7-4f30-bda3-8d514fd1d759.JPG)
![1](https://user-images.githubusercontent.com/88585596/156417711-26701cf4-7f38-4bf4-bff5-fc1cd40738e8.JPG)

## Reference
- https://github.com/mumble-07/emporia-wallet-app/tree/master/app

2022-03-03 15:53 UTC, kitkatpussycat commented on app/views/home/index.html.haml
> +This is home page!
add new line here

2022-03-03 15:56 UTC, kitkatpussycat requested changes

2022-03-03 15:56 UTC, kitkatpussycat commented on app/views/home/index.html.haml
> +This is home page!
add new line here..

2022-03-03 18:23 UTC, Zhi0105 commented on app/views/home/index.html.haml
> +This is home page!
This file already changed on my next PR

2022-03-04 10:49 UTC, analyn-cajocson approved these changes

2022-03-04 11:12 UTC, kitkatpussycat approved these changes

2022-03-04 11:13 UTC, merged